import type { Metadata } from 'next';
import { Footer } from '@/components/footer';
import Header from '@/components/header';
import localFont from 'next/font/local';

import '@/styles/global.module.scss';

// const nunitoMedium = localFont({
//   src: "../assets/fonts/nunito/Nunito-Medium.ttf",
// })

const oswaldMedium = localFont({
  src: '../assets/fonts/oswald/Oswald-Medium.ttf',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${oswaldMedium.className}`}>
        <Header />
        <div className="content">{children}</div>
        <Footer />
      </body>
    </html>
  );
}
